### ISSUE TITLE
Cuda out of memory with webui v1.6 (runpod template 1.9.0 and above)

### ISSUE THREAD

**Issue by aitrepreneur** [ashleykleynhans/stable-diffusion-docker#13]
Hey Ashleykleynhans,

first let me thank you for your amazing work, your runpod template is a godsend for SD training and testing :)

I just wanted to let you know that since yesterday (the release of your 1.9.0 v docker image) me and a lot of people are getting cuda out of memory errors when trying to train a Lora with kohya (using 24GB vram gpus)

I suspect it's because the 1.9.0 and above are using the newest auto1111 sd webui 1.6.0 and it's somehow using more vram than the previous version (I'm not sure, this is just speculation on my part).

Changing the template to a previous version works perfectly fine (anything before the 1.9.0 update) so that's not a big deal but most people are not aware of that which can create a lot of troubleshooting issues.

I don't know if you can do something about it or if I should just tell people to use older versions of the image if they get a cuda error, let me know.

Thanks again for your amazing work ;)

**Comment by ashleykleynhans** [comment]
Hi AItrepreneur,

Thanks for promoting my RunPod template in your tutorial, it is very much appreciated.

Looks like the latest v1.6.0 release of A1111 is using almost 5GB of VRAM just chilling and doing nothing.

<img width="271" alt="vram" src="https://github.com/ashleykleynhans/stable-diffusion-docker/assets/886709/06ce379c-8bb7-4110-a395-491c4e3e59ed">

I am pulling a previous version of my image that has A1111 v1.5.2 to check the difference.

It may be worth building an application that controls the other applications, for example giving users the ability to stop/start A1111, start/stop Kohya_ss, start/stop ComfyUI etc so that non-technical people can easily stop and start the applications from a front-end application rather than having to do it from the terminal.

**Comment by ashleykleynhans** [comment]
It actually looks like A1111 v1.5.2 also has a similar issue, but uses slightly less VRAM, so I guess the extra 2% usage on a 24GB GPU must be making a big difference.

<img width="1183" alt="Monosnap My Pods 2023-09-02 09-10-32" src="https://github.com/ashleykleynhans/stable-diffusion-docker/assets/886709/3bfcaa40-4c01-479d-8bb0-a7e7efb43a92">

I think stopping A1111 is a better temporary work-around than reverting back to a previous image version until I find time to build something to manage the various different applications.

A1111 can be stopped as follows:
```
fuser -k 3001/tcp
```
And started again as follows:
```
cd /workspace/stable-diffusion-webui
./webui.sh -f
```

**Comment by ashleykleynhans** [comment]
I've added an Application Manager which runs on port 8000 so that the various different applications can be stopped and started.  This can be used to stop A1111 when training Kohya_ss and then starting it again to test the trained model(s) once training is complete.

**Comment by aitrepreneur** [comment]
What a fantastic addition!!! This is just perfect! Thank you so much!
I just tried it out and it works perfectly now, thank you!
I will let everyone know in my next video how to use it! Again, thank you so much for your quick work!
